<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>_003_app3_vypis_obrazce</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\000-usefull-functions\usefull-functions.csproj" />
    <ProjectReference Include="..\usefull-functions\usefull-functions.csproj" />
  </ItemGroup>

</Project>
